apiVersion: v1
kind: PersistentVolume
metadata:
  name: jingu-character-service-mariadb-persistent-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mariadb-storage
  local:
    path: /mnt/disks/maria