apiVersion: v1
kind: Service
metadata:
  name: jingu-character-service-nginx
  labels:
    app: jingu-character-service
spec:
  type: NodePort
  ports:
  - nodePort: 30000
    port: 80
    targetPort: 3000
  selector:
    app: jingu-character-service