apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jingu-character-service-mariadb-persistent-volume-claim
  labels:
    app: jingu-character-service
spec:
  storageClassName: mariadb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi