apiVersion: v1
kind: Service
metadata:
  name: jingu-character-service-nginx
  labels:
    app: jingu-character-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: jingu-character-service