apiVersion: apps/v1
kind: Deployment
metadata:
  name: jingu-character-service
  labels:
    app: jingu-character-service
spec:
  selector:
    matchLabels:
      app: jingu-character-service
  replicas: 2
  template:
    metadata:
      labels:
        app: jingu-character-service
    spec:
      containers:
        - name: jingu-character-service
          image: aqourstokyo/jingu-app-service:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: http-server
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20